# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ex_0_0/design_1_ex_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ex_0_0 || ORIG_REF_NAME==design_1_ex_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_if_id_0_0/design_1_if_id_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_if_id_0_0 || ORIG_REF_NAME==design_1_if_id_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_id_ex_0_0/design_1_id_ex_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_id_ex_0_0 || ORIG_REF_NAME==design_1_id_ex_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_regs_0_0/design_1_regs_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_regs_0_0 || ORIG_REF_NAME==design_1_regs_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ifetch_0_0/design_1_ifetch_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ifetch_0_0 || ORIG_REF_NAME==design_1_ifetch_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_pc_reg_0_0/design_1_pc_reg_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_pc_reg_0_0 || ORIG_REF_NAME==design_1_pc_reg_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rom_0_0/design_1_rom_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rom_0_0 || ORIG_REF_NAME==design_1_rom_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_id_0_0/design_1_id_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_id_0_0 || ORIG_REF_NAME==design_1_id_0_0} -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
